import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import AppLayout from '@/components/app-layout/AppLayout'
import { Inter } from 'next/font/google'
import Section from '@/components/section/layout'
import FactsPage from './facts/page'
import { ThreeDButton } from '@/components/buttons/layout'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isOpen, setIsOpen] = useState(false); 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AppLayout> */}
      <div className={styles.wrapper}>
        <Section>
          <div className={styles.container}>
            <div className={styles.font}>
              Did You Know?
            </div>
          </div>
          <div className={styles.but}>
          <ThreeDButton onClick={() => setIsOpen(!isOpen)} />
          </div>
          {isOpen &&
          <FactsPage />
          }
        </Section>

      </div>
        {/* </AppLayout> */}

    </>
  )
}
